<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.5 Oppgaver | MET4 - Empiriske Metoder - Høst 2022</title>
  <meta name="description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="3.5 Oppgaver | MET4 - Empiriske Metoder - Høst 2022" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.5 Oppgaver | MET4 - Empiriske Metoder - Høst 2022" />
  
  <meta name="twitter:description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  

<meta name="author" content="Håkon Otneim og Geir Drage Berentsen" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="kjikvadrattester.html"/>
<link rel="next" href="relevante-r-testing.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link rel="apple-touch-icon" sizes="180x180" href="/met4/icon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/met4/icon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/met4/icon/favicon-16x16.png">
<link rel="manifest" href="/met4/icon/site.webmanifest">
<link rel="mask-icon" href="/met4/icon/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/met4/icon/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/met4/icon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<a href="https://www.nhh.no/"><img src="bilder/nhh.png" width="240"></a>
<li><a href="./index.html">MET4 - EMPIRISKE METODER</a></li>

<li class="divider"></li>
<li><a href="index.html#innledning" id="toc-innledning">Innledning</a></li>
<li><a href="introduksjon-til-r.html#introduksjon-til-r" id="toc-introduksjon-til-r"><span class="toc-section-number">1</span> Introduksjon til R</a>
<ul>
<li><a href="en-gjennomgang-av-rstudio.html#en-gjennomgang-av-rstudio" id="toc-en-gjennomgang-av-rstudio"><span class="toc-section-number">1.1</span> En gjennomgang av RStudio</a></li>
<li><a href="enkle-beregninger-og-variabler.html#enkle-beregninger-og-variabler" id="toc-enkle-beregninger-og-variabler"><span class="toc-section-number">1.2</span> Enkle beregninger og variabler</a></li>
<li><a href="vektorer.html#vektorer" id="toc-vektorer"><span class="toc-section-number">1.3</span> Vektorer</a></li>
<li><a href="pakker.html#pakker" id="toc-pakker"><span class="toc-section-number">1.4</span> Pakker</a></li>
<li><a href="mappesti.html#mappesti" id="toc-mappesti"><span class="toc-section-number">1.5</span> Mappesti</a></li>
<li><a href="innlesing-av-data.html#innlesing-av-data" id="toc-innlesing-av-data"><span class="toc-section-number">1.6</span> Innlesing av data</a></li>
<li><a href="statistiske-analyser.html#statistiske-analyser" id="toc-statistiske-analyser"><span class="toc-section-number">1.7</span> Statistiske analyser</a></li>
<li><a href="r-plotting.html#r-plotting" id="toc-r-plotting"><span class="toc-section-number">1.8</span> Plotting</a></li>
<li><a href="script.html#script" id="toc-script"><span class="toc-section-number">1.9</span> Script</a></li>
<li><a href="pipe.html#pipe" id="toc-pipe"><span class="toc-section-number">1.10</span> Pipe-operatoren <code>%&gt;%</code> og enkel datavask</a></li>
<li><a href="r-ekstra.html#r-ekstra" id="toc-r-ekstra"><span class="toc-section-number">1.11</span> Oppsummering og ekstra oppgaver</a></li>
</ul></li>
<li><a href="grunnleggende-statistikk.html#grunnleggende-statistikk" id="toc-grunnleggende-statistikk"><span class="toc-section-number">2</span> Grunnleggende statistikk</a>
<ul>
<li><a href="deskriptiv-statistikk.html#deskriptiv-statistikk" id="toc-deskriptiv-statistikk"><span class="toc-section-number">2.1</span> Deskriptiv statistikk</a></li>
<li><a href="utvalg-og-estimering.html#utvalg-og-estimering" id="toc-utvalg-og-estimering"><span class="toc-section-number">2.2</span> Utvalg og estimering</a></li>
<li><a href="oppgaverdeskriptiv.html#oppgaverdeskriptiv" id="toc-oppgaverdeskriptiv"><span class="toc-section-number">2.3</span> Oppgaver</a></li>
<li><a href="relevant-r-grunnleggende.html#relevant-r-grunnleggende" id="toc-relevant-r-grunnleggende"><span class="toc-section-number">2.4</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="hypotesetesting.html#hypotesetesting" id="toc-hypotesetesting"><span class="toc-section-number">3</span> Hypotesetesting</a>
<ul>
<li><a href="generelt-om-hypotesetesting.html#generelt-om-hypotesetesting" id="toc-generelt-om-hypotesetesting"><span class="toc-section-number">3.1</span> Generelt om hypotesetesting</a></li>
<li><a href="enpop.html#enpop" id="toc-enpop"><span class="toc-section-number">3.2</span> Inferens om en populasjon</a></li>
<li><a href="inferens-om-to-populasjoner.html#inferens-om-to-populasjoner" id="toc-inferens-om-to-populasjoner"><span class="toc-section-number">3.3</span> Inferens om to populasjoner</a></li>
<li><a href="kjikvadrattester.html#kjikvadrattester" id="toc-kjikvadrattester"><span class="toc-section-number">3.4</span> Kjikvadrattester</a></li>
<li><a href="oppgaver.html#oppgaver" id="toc-oppgaver"><span class="toc-section-number">3.5</span> Oppgaver</a></li>
<li><a href="relevante-r-testing.html#relevante-r-testing" id="toc-relevante-r-testing"><span class="toc-section-number">3.6</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="regresjon.html#regresjon" id="toc-regresjon"><span class="toc-section-number">4</span> Regresjon</a>
<ul>
<li><a href="enkel-regresjon.html#enkel-regresjon" id="toc-enkel-regresjon"><span class="toc-section-number">4.1</span> Enkel regresjon</a></li>
<li><a href="multippel-regresjon.html#multippel-regresjon" id="toc-multippel-regresjon"><span class="toc-section-number">4.2</span> Multippel regresjon</a></li>
<li><a href="modellbygging.html#modellbygging" id="toc-modellbygging"><span class="toc-section-number">4.3</span> Modellbygging</a></li>
<li><a href="oppgaver-1.html#oppgaver-1" id="toc-oppgaver-1"><span class="toc-section-number">4.4</span> Oppgaver</a></li>
<li><a href="relevante-r-regresjon.html#relevante-r-regresjon" id="toc-relevante-r-regresjon"><span class="toc-section-number">4.5</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="tidsrekker.html#tidsrekker" id="toc-tidsrekker"><span class="toc-section-number">5</span> Tidsrekker</a>
<ul>
<li><a href="intro.html#intro" id="toc-intro"><span class="toc-section-number">5.1</span> Introduksjon til tidsrekker</a></li>
<li><a href="trend-og-sesong.html#trend-og-sesong" id="toc-trend-og-sesong"><span class="toc-section-number">5.2</span> Trend og sesong</a></li>
<li><a href="ar.html#ar" id="toc-ar"><span class="toc-section-number">5.3</span> AR(p)</a></li>
<li><a href="stasjonaritet.html#stasjonaritet" id="toc-stasjonaritet"><span class="toc-section-number">5.4</span> Stasjonaritet</a></li>
<li><a href="autokorrelasjon.html#autokorrelasjon" id="toc-autokorrelasjon"><span class="toc-section-number">5.5</span> Autokorrelasjon</a></li>
<li><a href="ma.html#ma" id="toc-ma"><span class="toc-section-number">5.6</span> MA(q)</a></li>
<li><a href="arma-arima.html#arma-arima" id="toc-arma-arima"><span class="toc-section-number">5.7</span> ARMA og ARIMA</a></li>
<li><a href="modellbygging-1.html#modellbygging-1" id="toc-modellbygging-1"><span class="toc-section-number">5.8</span> Modellbygging</a></li>
<li><a href="oppgaver-2.html#oppgaver-2" id="toc-oppgaver-2"><span class="toc-section-number">5.9</span> Oppgaver</a></li>
<li><a href="relevante-r-tidsrekker.html#relevante-r-tidsrekker" id="toc-relevante-r-tidsrekker"><span class="toc-section-number">5.10</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="avansert-regresjon-og-maskinlæring.html#avansert-regresjon-og-maskinlæring" id="toc-avansert-regresjon-og-maskinlæring"><span class="toc-section-number">6</span> Avansert regresjon og maskinlæring</a>
<ul>
<li><a href="logistisk-regresjon.html#logistisk-regresjon" id="toc-logistisk-regresjon"><span class="toc-section-number">6.1</span> Logistisk regresjon</a></li>
<li><a href="introduksjon-til-maskinlæring-med-knn.html#introduksjon-til-maskinlæring-med-knn" id="toc-introduksjon-til-maskinlæring-med-knn"><span class="toc-section-number">6.2</span> Introduksjon til maskinlæring med kNN</a></li>
<li><a href="paneldata.html#paneldata" id="toc-paneldata"><span class="toc-section-number">6.3</span> Paneldata</a></li>
<li><a href="oppgaver-3.html#oppgaver-3" id="toc-oppgaver-3"><span class="toc-section-number">6.4</span> Oppgaver</a></li>
<li><a href="relevante-r-avansert-regresjon.html#relevante-r-avansert-regresjon" id="toc-relevante-r-avansert-regresjon"><span class="toc-section-number">6.5</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="dataøvinger.html#dataøvinger" id="toc-dataøvinger"><span class="toc-section-number">7</span> Dataøvinger</a>
<ul>
<li><a href="dataøving-1.html#dataøving-1" id="toc-dataøving-1"><span class="toc-section-number">7.1</span> Dataøving 1</a></li>
<li><a href="dataøving-2.html#dataøving-2" id="toc-dataøving-2"><span class="toc-section-number">7.2</span> Dataøving 2</a></li>
<li><a href="dataøving-3.html#dataøving-3" id="toc-dataøving-3"><span class="toc-section-number">7.3</span> Dataøving 3</a></li>
<li><a href="dataøving-4.html#dataøving-4" id="toc-dataøving-4"><span class="toc-section-number">7.4</span> Dataøving 4</a></li>
<li><a href="dataøving-5.html#dataøving-5" id="toc-dataøving-5"><span class="toc-section-number">7.5</span> Dataøving 5</a></li>
</ul></li>
<li><a href="seminar.html#seminar" id="toc-seminar"><span class="toc-section-number">8</span> Seminaroppgaver</a>
<ul>
<li><a href="seminar-1---grunnleggende-statistikk.html#seminar-1---grunnleggende-statistikk" id="toc-seminar-1---grunnleggende-statistikk"><span class="toc-section-number">8.1</span> Seminar 1 - Grunnleggende statistikk</a></li>
<li><a href="seminar-2---hypotesetesting.html#seminar-2---hypotesetesting" id="toc-seminar-2---hypotesetesting"><span class="toc-section-number">8.2</span> Seminar 2 - Hypotesetesting</a></li>
<li><a href="seminar-3---regresjon-i.html#seminar-3---regresjon-i" id="toc-seminar-3---regresjon-i"><span class="toc-section-number">8.3</span> Seminar 3 - Regresjon I</a></li>
<li><a href="seminar-4---regresjon-ii.html#seminar-4---regresjon-ii" id="toc-seminar-4---regresjon-ii"><span class="toc-section-number">8.4</span> Seminar 4 - Regresjon II</a></li>
<li><a href="seminar-5---tidsrekker.html#seminar-5---tidsrekker" id="toc-seminar-5---tidsrekker"><span class="toc-section-number">8.5</span> Seminar 5 - Tidsrekker</a></li>
<li><a href="seminar-6---avansert-regresjon-og-maskinlæring.html#seminar-6---avansert-regresjon-og-maskinlæring" id="toc-seminar-6---avansert-regresjon-og-maskinlæring"><span class="toc-section-number">8.6</span> Seminar 6 - Avansert regresjon og maskinlæring</a></li>
</ul></li>
<li><a href="eksamensoppgaver.html#eksamensoppgaver" id="toc-eksamensoppgaver"><span class="toc-section-number">9</span> Eksamensoppgaver</a>
<ul>
<li><a href="skoleeksamen.html#skoleeksamen" id="toc-skoleeksamen"><span class="toc-section-number">9.1</span> Tidligere eksamensoppgaver (skoleeksamen)</a></li>
<li><a href="tidligere-eksamensoppgaver-hjemmeeksamen.html#tidligere-eksamensoppgaver-hjemmeeksamen" id="toc-tidligere-eksamensoppgaver-hjemmeeksamen"><span class="toc-section-number">9.2</span> Tidligere eksamensoppgaver (hjemmeeksamen)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.nhh.no/en/employees/faculty/hakon-otneim/">Håkon Otneim</a></li>
<li><a href="https://www.nhh.no/en/employees/faculty/geir-drage-berentsen/">Geir Drage Berentsen</a></li>
<li><a href="https://github.com/rstudio/bookdown">
Publisert ved hjelp av bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MET4 - Empiriske Metoder - Høst 2022</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="oppgaver" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Oppgaver</h2>
<div id="standard-oppgaver-1" class="section level3" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Standard oppgaver</h3>
<p>Introduksjon til hypotesetesting</p>
<ol style="list-style-type: decimal">
<li>For hvert av scenarioene i a og b, gjør følgende:
<ul>
<li>Sett opp relevant nullhypotese og alternativhypotese (hint: nullhypotese avhenger av hvor ‘bevisbyrden’ bør ligge)</li>
<li>Definer type I-og type II-feil.</li>
<li>Diskuter konsekvensene av type I-feil og type II-feil i det aktuelle scenarioet.</li>
</ul>
<ol style="list-style-type: lower-alpha">
<li><p>En ny type medisin skal vurderes for kommersialisering. Du sitter i et vurderingspanel som skal vurdere om medisinen kan bli godkjent eller ikke.</p></li>
<li><p>Du blir presentert to ulike investeringer å velge mellom. En av dem er veldig risikabel, men med stor potensiell profitt. Den andre er mindre risikabel, men med lavere potensiell profitt.</p></li>
</ol></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(H_0\)</span>: Den nye medisinen er ikke trygg og effektiv. <span class="math inline">\(H_1\)</span>: Den nye medisinen er trygg og effektiv. Type I-feil: Forkaste <span class="math inline">\(H_0\)</span> når <span class="math inline">\(H_0\)</span> er sann. Konsekvens: Risikerer at vi begynner å produsere en medisin som ikke er trygg og effektiv. Type II-feil: Forkaster <em>ikke</em> <span class="math inline">\(H_0\)</span> når <span class="math inline">\(H_1\)</span> er sann. Konsekvens: Vi lar være å produsere en medisin som faktisk er trygg og effektiv.</li>
</ol>
<p>Kommentar: Signifikansnivået ved produksjon av medisiner settes ofte lavt fordi konsekvensene av en type I-feil kan være svært alvorlige.</p>
</blockquote>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li><span class="math inline">\(H_0\)</span>: Den mest risikable investeringen er mest lønnsom. <span class="math inline">\(H_1\)</span>: Den mest risikable investeringen er ikke mest lønnsom. Type I-feil: Forkaste <span class="math inline">\(H_0\)</span> når <span class="math inline">\(H_0\)</span> er sann. Konsekvens:Vi investerer i den minst risikable investeringen, som ikke er mest lønnsom. Type II-feil: Forkaster <em>ikke</em> <span class="math inline">\(H_0\)</span> når <span class="math inline">\(H_1\)</span> er sann. Konsekvens: Vi investerer i den mest risikable investeringen, som ikke er mest lønnsom.</li>
</ol>
</blockquote>
</details>
<ol start="2" style="list-style-type: decimal">
<li><p>Vi har følgende hypoteser og informasjon om dataene: <span class="math inline">\(H_0: \mu = 150\)</span> mot <span class="math inline">\(H_1: \mu \neq 150\)</span>. <span class="math inline">\(\sigma = 10\)</span>, <span class="math inline">\(n =100\)</span>, <span class="math inline">\(\overline{x} = 150\)</span>.</p>
<p>Bestem verdi av testobservator, forkastelsesområde dersom signifikansnivået er <span class="math inline">\(\alpha = 0.05\)</span>, og p-verdi. Konkluder.</p></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<p>Her er <span class="math inline">\(\sigma\)</span> kjent så vi kan bruke en z-observator. Forkastelsesområde <span class="math inline">\(Z &lt; -z_{0.025}=-1.96\)</span> eller <span class="math inline">\(Z&gt; z_{0.025}=1.96\)</span>.</p>
<p><span class="math display">\[Z = \frac{\overline{x} - \mu}{\sigma/\sqrt{n}} = \frac{150 - 150}{10/\sqrt{100}}=0\]</span></p>
<p>p-verdi<span class="math inline">\(=2P(Z &gt; 0) = 2\times0.5=1\)</span>. Vi kan ikke forkaste nullhypotesen <span class="math inline">\(H_0: \mu = 0\)</span>. Faktisk er det ekstremt sannsynlig (p-verdi = 1) å observere det vi har observert dersom nullhypotesen er sann.</p>
</blockquote>
</details>
<ol start="3" style="list-style-type: decimal">
<li><p>Vi har følgende hypoteser og informasjon om dataene: <span class="math inline">\(H_0: \mu = 55\)</span> mot <span class="math inline">\(H_1: \mu &gt; 55\)</span>.
<span class="math inline">\(\sigma = 20\)</span>, <span class="math inline">\(n = 25\)</span>, <span class="math inline">\(\overline{x} = 67\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Regn ut testobservatoren <span class="math inline">\(Z\)</span>.</p></li>
<li><p>Regn ut p-verdi.</p></li>
<li><p>Regn ut p-verdi, denne gangen med <span class="math inline">\(\overline{x}\)</span> = 63.</p></li>
<li><p>Regn ut p-verdi, denne gangen med <span class="math inline">\(\overline{x}\)</span> = 59.</p></li>
<li><p>Fastslå hva som skjer med verdien av testobservatoren (Z) og p-verdien når <span class="math inline">\(\overline{x}\)</span> nærmer seg <span class="math inline">\(55\)</span> (verdien av <span class="math inline">\(\mu\)</span> under <span class="math inline">\(H_0\)</span>).</p></li>
</ol></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math display">\[Z = \frac{\overline{x} - \mu}{\sigma/\sqrt{n}} = \frac{67 - 55}{20/\sqrt{25}}=3\]</span></p></li>
<li><p><span class="math inline">\(\text{p-verdi} = P(Z &gt; 3.00) = 1 – P(Z&lt;3) = 1 – 0.9987 = 0.0013\)</span>. Kommentar: Her kan du bruke <code>pnorm(3)</code> i R til å regne ut <span class="math inline">\(P(Z&lt;3)\)</span>.</p></li>
<li><p>Ny verdi av testobservator blir da <span class="math inline">\(Z = 2\)</span>.
<span class="math inline">\(\text{p-verdi} = P(Z &gt; 2.00) = 1 – 0.9772 = 0.0228\)</span>.</p></li>
<li><p>Ny verdi av testobservator blir da <span class="math inline">\(Z = 1\)</span>.
<span class="math inline">\(\text{p-verdi} = P(Z &gt; 1.00) = 1 – 0.8413 = 0.1587\)</span>.</p></li>
<li><p>Vi ser at testobservatoren minker og p-verdien øker når <span class="math inline">\(\overline{x}\)</span> nærmer seg <span class="math inline">\(55\)</span>.</p></li>
</ol>
<p>Forklaring: La <span class="math inline">\(\mu_0 = 55\)</span> være verdien av <span class="math inline">\(\mu\)</span> under <span class="math inline">\(H_0\)</span>. Z-observatoren måler avviket mellom antagelsen under <span class="math inline">\(H_0\)</span> og dataene vi observerer og avtar derfor når vår observasjon av <span class="math inline">\(\overline{x}\)</span> nærmer seg <span class="math inline">\(\mu_0\)</span>. P-verdien sier hvor sannsynlig det er å observere de dataene vi har dersom <span class="math inline">\(H_0\)</span> er sann og øker følgelig når <span class="math inline">\(\overline{x}\)</span> nærmer seg <span class="math inline">\(\mu_0\)</span>.</p>
</blockquote>
</details>
<ol start="4" style="list-style-type: decimal">
<li><p>Annta at vi har følgende hypoteser og informasjon om dataene: <span class="math inline">\(H_0: \mu = 50\)</span> mot <span class="math inline">\(H_1: \mu &gt; 50\)</span>. <span class="math inline">\(\sigma = 10\)</span>, <span class="math inline">\(n = 40\)</span>, <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p>Bestem <span class="math inline">\(\beta\)</span>, altså sannsynligheten for en type-II feil, under antagelsen at <span class="math inline">\(\mu = 55\)</span>.</p></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<p>Forkastningsområdet blir da</p>
<p><span class="math display">\[Z = \frac{\overline{X} - 50}{10/\sqrt{40}} &gt; Z_{0.05} = 1.645 \]</span>
dvs at vi forkaster <span class="math inline">\(H_0\)</span> når
<span class="math display">\[\overline{X} &gt; 50 + 1.645\times\frac{10}{\sqrt{40}}=52.6\]</span>
En type-II feil svarer til å <em>ikke</em> forkaste <span class="math inline">\(H_0\)</span> når <span class="math inline">\(H_1\)</span> er sann. For å regne på sannsynligheten for type-II feil må vi ikke bare anta at <span class="math inline">\(H_1\)</span> er sann, men være spesifike på hva verdien til <span class="math inline">\(\mu\)</span> er (i dette tilfellet 55). Vi lurer altså på hva sannsynligheten for at vi <em>ikke</em> er i forkastnings området (<span class="math inline">\(\overline{X} &lt; 52.6\)</span>) gitt at <span class="math inline">\(\mu = 55\)</span>:
<span class="math display">\[\begin{equation*}
\begin{split}
\beta &amp;= P(\overline{X} &lt; 52.6\quad\text{gitt at $\mu = 55$})\\
&amp;= P(\frac{\overline{X} - 55}{10/\sqrt{40}} &lt; \frac{52.6 - 55}{10/\sqrt{40}})\\
&amp;=P(Z &lt; -1.52) = 0.064
\end{split}
\end{equation*}\]</span>
Merk: Et begrep som ofte blir brukt om tester er <em>styrken</em> til testen <span class="math inline">\(1-\beta\)</span> som da er sannsynligheten for å forkaste <span class="math inline">\(H_0\)</span> når <span class="math inline">\(H_1\)</span> er sann. En god test har god (stor) styrke. Hadde vi gjentatt denne testen mange ganger ville vi ha forkastet <span class="math inline">\(H_0\)</span> i <span class="math inline">\((100 - 6.4)\% = 93.6\%\)</span> av gangene dersom det faktisk er slik at sann <span class="math inline">\(\mu\)</span> er 55.</p>
</blockquote>
</details>
<ol start="5" style="list-style-type: decimal">
<li><p>En leder frykter at den gjennomsnittlige tiden ansatte daglig bruker på sosiale medier overstiger 45 minutter. For å teste denne mistanken, plukker han ut et tilfeldig utvalg på 15 personer, og spør om tid brukt på sosiale medier etter en tilfeldig arbeidsdag. Resultatene er oppsummert nedenfor.</p>
<pre><code>  70, 96, 58, 88, 34, 42, 34, 56, 68, 46, 26, 18, 22, 60, 84</code></pre>
<ol style="list-style-type: lower-alpha">
<li><p>Hvis samlingen av tider er normalfordelt med standardavvik på 20 minutter, kan lederen hevde at mistanken hans stemmer på et 1 % signifikans-nivå?</p></li>
<li><p>Tror du observasjonene over er et representativt utvalg? Hva kunne lederen gjort annerledes?</p></li>
</ol></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Lederen ønsker altså å teste <span class="math inline">\(H_0: \mu = 45\)</span> mot alternativ hypotesen <span class="math inline">\(H_1: \mu &gt; 45\)</span>. Testobservatoren er da gitt ved</li>
</ol>
<p><span class="math display">\[Z = \frac{\overline{X} - \mu_0}{\sigma/\sqrt{n}} = \frac{53.46 - 45}{20/\sqrt{15}} = 1.64\]</span></p>
<p>Sannsynligheten for å observerer noe minst like ekstremt og til fordel for <span class="math inline">\(H_1\)</span> (p-verdien) er da</p>
<p><span class="math display">\[P-verdi = P(Z &gt; 1.645) \approx 0.05 &gt; 0.01\]</span>.</p>
<p>Lederen kan altså ikke trekke denne konklusjonen på 1 % signifikansnivå. For å forkaste null hypotesen på et 1 % signifikansnivå, måtte vi hatt p-verdi lavere enn 1 %.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Dersom lederen spør ansatte fjes til fjes er det nærliggende å tro at de ansatte vil underdrive sin bruk av sosiale medier. En anonym spørreundersøkelse ville nok gitt et mer representativt utvalg.</li>
</ol>
</blockquote>
</details>
<ol start="6" style="list-style-type: decimal">
<li><p>Gjennomsnitt og standardavvik i et utvalg på <span class="math inline">\(n=100\)</span> er <span class="math inline">\(\overline{x} = 20\)</span> og <span class="math inline">\(s = 2\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Finn 95 % konfidensintervall av gjennomsnitt (<span class="math inline">\(\mu\)</span>) i populasjonen.</p></li>
<li><p>Gjenta a. med <span class="math inline">\(s = 5\)</span>.</p></li>
<li><p>Gjenta a. med <span class="math inline">\(s = 10\)</span>.</p></li>
<li><p>Fastslå hvordan det estimerte konfidensintervallet endrer seg når vi øker <span class="math inline">\(s\)</span>.</p></li>
<li><p>Anta at <span class="math inline">\(s=5\)</span> og regn et 95 % konfidensintervall dersom størrelsen på utvalget er henholdsvis <span class="math inline">\(n = 50\)</span> og <span class="math inline">\(n=10\)</span>.</p></li>
<li><p>Fastlå hvordan det estimerte konfidensintervallet endrer seg når vi øker <span class="math inline">\(n\)</span>.</p></li>
</ol></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li><p><span class="math display">\[\overline{x} \pm t_{\alpha/2, n - 1}s/\sqrt{n} = 20 \pm 1.984\times 2/\sqrt{100} = [19.60 ,20.40]\]</span></p></li>
<li><p><span class="math display">\[ 20 \pm 1.984\times 5/\sqrt{100} = [19.01 ,20.99]\]</span></p></li>
<li><p><span class="math display">\[ 20 \pm 1.984\times 10/\sqrt{100} = [18.02 ,21.98]\]</span></p></li>
<li><p>Konfidensintervallet blir større når <span class="math inline">\(s\)</span> øker.</p></li>
<li><p><span class="math display">\[\overline{x} \pm t_{\alpha/2, n - 1}s/\sqrt{n} = 20 \pm 2.09\times 5/\sqrt{50} = [18.58 ,21.42]\]</span>
<span class="math display">\[\overline{x} \pm t_{\alpha/2, n - 1}s/\sqrt{n} = 20 \pm 2.26\times 5/\sqrt{10} = [16.42 ,23.58]\]</span></p></li>
<li><p>Vi ser at jo større <span class="math inline">\(n\)</span> er jo mindre blir konfidensintervallet. Flere observasjoner gjør at vi med større sikkerhet (smalere intervall) kan si hvor <span class="math inline">\(\mu\)</span> ligger.</p></li>
</ol>
</blockquote>
</details>
<ol start="7" style="list-style-type: decimal">
<li>Med sterkt fall i flyreiser og passasjerer på grunn av koronakrisen virker det sannsynlig at det blir færre forsinkelser i flytrafikken. Før krisen hevdet et flyselskap at de landet presist 92 % av flyreisene. I et tilfeldig utvalg flyreiser hos det samme selskapet under krisen ble 148 av 165 vurdert til å være presise. Kan vi konkludere på 5 % signifikansnivå at det er færre forsinkelser under koronakrisen?</li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<p>La <span class="math inline">\(p\)</span> være den sanne andelen av flyreiser som blir forsinket under krisen. Vi skal da teste <span class="math inline">\(H_0: p = 0.92\)</span> mot <span class="math inline">\(H_1: p &lt; 0.92\)</span>. Vårt estimat på <span class="math inline">\(p\)</span> er <span class="math inline">\(\hat{p}=148/165 \approx 0.90\)</span> og testobservatoren er gitt ved</p>
</blockquote>
<blockquote>
<p><span class="math display">\[z = \frac{\hat{p} - p_0}{\sqrt{p_0(1 - p_0)/n}} = \frac{0.90 - 0.92}{\sqrt{0.92(1 - 0.92)/165}} \approx -0.95\]</span>
Dersom vi bruker kritisk verdi ville forkastningsområdet vært <span class="math inline">\(z &lt; -1.645\)</span> og siden <span class="math inline">\(z&gt; -1.645\)</span> kan vi altså ikke forkaste <span class="math inline">\(H_0\)</span>. Alternativt kan vi regne ut p-verdien som er “sannsynligheten for det vi har observert eller noe enda mer til fordel for <span class="math inline">\(H_1\)</span>. En enda mer negativ verdi enn -0.95 ville vært til fordel for <span class="math inline">\(H_1\)</span>, derfor er</p>
</blockquote>
<blockquote>
<p><span class="math display">\[p-verdi = P(Z &lt; - 0.95) = 0.17\]</span>
og vi kan derfor <em>ikke</em> forkaste <span class="math inline">\(H_0\)</span> siden p-verdien <em>ikke</em> er mindre enn 0.05.</p>
</blockquote>
</details>
<ol start="8" style="list-style-type: decimal">
<li>Vi har følgende informasjon fra to tilfeldige utvalg fra to ulike normalfordelte populasjoner: <span class="math inline">\(\overline{x}_1 = 400\)</span>, <span class="math inline">\(s_1 = 130\)</span>, <span class="math inline">\(n_1 = 130\)</span>, <span class="math inline">\(\overline{x}_2 = 390\)</span>, <span class="math inline">\(s_2 = 50\)</span>, <span class="math inline">\(n_2 = 130\)</span>.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Kan vi hevde på et 5 % signifikansnivå at <span class="math inline">\(\mu_1\)</span> er større enn <span class="math inline">\(\mu_2\)</span>? Det oppgis at</li>
</ol>
<p><span class="math display">\[\nu =  \frac{\left(\frac{s^2_{1}}{n_1} + \frac{s^2_{2}}{n_2}\right)^2}{\left(\frac{s^2_{1}}{n_1}\right)^2/(n_1 - 1) + \left(\frac{s^2_{2}}{n_2}\right)^2/(n_2 - 1)}\approx 166\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>Gjenta a., denne gangen med <span class="math inline">\(s_1 = 30\)</span> og <span class="math inline">\(s_2 = 15\)</span>. Som over, oppgis det at <span class="math inline">\(\nu \approx 190\)</span>.</p></li>
<li><p>Fastslå hva som skjer hvis utvalgenes standardavvik blir mindre.</p></li>
<li><p>Gjenta a., denne gangen med utvalg på <span class="math inline">\(n_1 = n_2 = 20\)</span> observasjoner. Som over, oppgis det at <span class="math inline">\(\nu \approx 28\)</span>.</p></li>
<li><p>Fastslå effekten av å redusere utvalgsstørrelser.</p></li>
</ol>
<details>
<summary>
Løsning
</summary>
<ol style="list-style-type: lower-alpha">
<li>Vi skal altså teste <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span> mot <span class="math inline">\(H_1: \mu_1 - \mu_2 &gt; 0\)</span>. Siden variansene i utvalget er såpass ulike antar vi at vi må bruke varianten av testen med ulik varians. Testobservatoren er da gitt ved</li>
</ol>
<p><span class="math display">\[T = \frac{\overline{x}_1 - \overline{x}_2 - 0}{\sqrt{\frac{s^2_{1}}{n_1} + \frac{s^2_{2}}{n_2}}}=\frac{400 - 390}{\sqrt{\frac{130^2}{130} + \frac{50^2}{130}}} = 0.82\]</span>
Antall frihetsgrader oppgis til å være <span class="math inline">\(v \approx 166\)</span>. Vi forkaster <span class="math inline">\(H_0\)</span> dersom <span class="math inline">\(T &gt; t_{0.05, 166} = 1.654\)</span>, og siden dette <em>ikke</em> er tilfelle her kan vi <em>ikke</em> forkaste <span class="math inline">\(H_0\)</span> ved 5 % signifikansnivå.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Testobservatoren blir i dette tilfellet</li>
</ol>
<p><span class="math display">\[T = \frac{\overline{x}_1 - \overline{x}_2 - 0}{\sqrt{\frac{s^2_{1}}{n_1} + \frac{s^2_{2}}{n_2}}}=\frac{400 - 390}{\sqrt{\frac{30^2}{130} + \frac{15^2}{130}}} = 3.40\]</span>
Antall frihetsgrader oppgis til å være <span class="math inline">\(v \approx 190\)</span>. Siden <span class="math inline">\(T = 3.40 &gt; t_{0.05, 190} = 1.653\)</span> forkaster vi <span class="math inline">\(H_0\)</span> på 5 % signifikansnivå.</p>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>Når standardavvikene i utvalgene blir mindre øker verdien av testobservatoren. Mindre standardavvik betyr at vi er mer sikre på at <span class="math inline">\(\overline{x}_1 - \overline{x}_2\)</span> ligger nær <span class="math inline">\(\mu_1 - \mu_2\)</span>, og at en evt. differanse kan tyde på avvik fra <span class="math inline">\(H_0\)</span>. Dette blir reflektert av en større testobservator.</p></li>
<li><p>Testobservatoren blir da</p></li>
</ol>
<p><span class="math display">\[T = \frac{\overline{x}_1 - \overline{x}_2 - 0}{\sqrt{\frac{s^2_{1}}{n_1} + \frac{s^2_{2}}{n_2}}}=\frac{400 - 390}{\sqrt{\frac{130^2}{20} + \frac{50^2}{20}}} = 0.32\]</span>
Antall frihetsgrader oppgis til å være <span class="math inline">\(v \approx 28\)</span>. Vi forkaster <span class="math inline">\(H_0\)</span> dersom <span class="math inline">\(T &gt; t_{0.05, 28} = 1.701\)</span>, og siden dette <em>ikke</em> er tilfelle her kan vi <em>ikke</em> forkaste <span class="math inline">\(H_0\)</span> ved 5 % signifikansnivå.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Få observasjoner representerer større usikkerhet om differansen <span class="math inline">\(\overline{x}_1 - \overline{x}_2\)</span> bare skyldes tilfeldighet, og dette reflekteres av testobservatoren som vil synke når utvalgsstørrelsen reduseres.</li>
</ol>
<!-- m1 <- 400 -->
<!-- m2 <- 390 -->
<!-- s1 <- 130 -->
<!-- s2 <- 50 -->
<!-- n1  <- n2 <- 20 -->
<!-- t <- (m1 - m2)/sqrt(s1^2/n1 + s2^2/n2) -->
<!-- v <- (s1^2/n1 + s2^2/n2)^2/((s1^2/n1)^2/(n1 - 1) + (s2^2/n2)^2/(n2 - 1)) -->
<!-- qt(0.95, v) -->
</details>
<ol start="9" style="list-style-type: decimal">
<li><p>Et nystartet firma har utviklet to løsninger for automatisk registrering av av antall lus på oppdrettslaks. Metode A er litt dyrere enn metode B, men firmaet mener Metode A en den raskeste metoden. For å teste ut denne hypotesen blir begge metodene brukt til å registrere lus på 11 basseng av ulik størrelse og med forskjellig antall fisk. Antall minutter hver metode tar blir registrert for hvert basseng.</p>
<ol style="list-style-type: lower-alpha">
<li>Under er det gitt en R-utskrift fra en to-utvalgs t-test. Still opp nullhypotesen og den alternative hypotesen i samsvar med R-utskriften. Bruk også utskriften til å formulere en konklusjon for en test med 5% signifikansnivå.</li>
</ol></li>
</ol>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  metodeB and metodeA
## t = 1.6129, df = 18.969, p-value = 0.06164
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  -0.7959228        Inf
## sample estimates:
## mean of x mean of y 
##  83.44886  72.41662</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Under er det gitt en R-utskrift fra en paret t-test for de samme dataene. Still opp nullhypotesen og den alternative hypotesen i samsvar med R-utskriften. Formuler testobservatoren og bruk også utskriften til å formulere en konklusjon for en test med 5% signifikansnivå.</li>
</ol>
<pre><code>## 
##  Paired t-test
## 
## data:  metodeB and metodeA
## t = 5.4477, df = 10, p-value = 0.0001409
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  7.361811      Inf
## sample estimates:
## mean of the differences 
##                11.03225</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>Hvilke av de to foregående testene bør en bruke i dette tilfellet?</li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>La <span class="math inline">\(\mu_1\)</span> og <span class="math inline">\(\mu_2\)</span> være forventet tid til registrering av lus i et basseng for hhv metode B og metode A. Da er R-utskriften en test av <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span> mot det enside alternativet <span class="math inline">\(H_1: \mu_1-\mu_2 &gt; 0\)</span>. Fra utskriften ser vi at <span class="math inline">\(p-value= 0.06164 &gt; 0.05\)</span>, altså kan vi ikke forkaste <span class="math inline">\(H_0\)</span> ved <span class="math inline">\(5\%\)</span> signifikansnivå.</li>
</ol>
<p>Praktisk tolkning: Vi kan ikke konkludere med at det er noe forskjell i tiden de to metodene bruker.</p>
<p>b.I en paret t-test baserer vil testen på de parvise differansene <span class="math inline">\(d_i = x_i - y_i\)</span>, der <span class="math inline">\(x_i\)</span> og <span class="math inline">\(y_i\)</span> er tiden hhv metode B og A bruker på å registrere lus i basseng nr. i. Utskriften viser en test av <span class="math inline">\(H_0: \mu_d = 0\)</span> mot det ensidige alternativet <span class="math inline">\(H_1: \mu_d &gt; 0\)</span>. Testobservatoren er da gitt ved</p>
<p><span class="math display">\[T=\frac{\overline{d}-0}{s_d/\sqrt{n}}\]</span></p>
<p>Fra utskriften ser vi at <span class="math inline">\(p-value= 0.0001409 &lt; 0.05\)</span>, altså kan vi forkaste <span class="math inline">\(H_0\)</span> ved <span class="math inline">\(5\%\)</span> signifikansnivå.</p>
<p>Praktisk tolkning: Det ser ut til at metode A er raskere enn metode B.</p>
</blockquote>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>En paret t-test er generelt det riktige valget dersom observasjonene som blir “paret” er avhengige. I dette tilfellet er det naturlig å tro at tiden metode A og B bruker på et basseng er avhengige størrelser (f.eks vil et basseng med mye fisk ta lang tid å registrere for begge metodene). I en to-utvalgs t-test antar vi derimot at tiden det tar for metode A og B å registrere lus for et basseng er uavhengige.</li>
</ol>
</blockquote>
</details>
<ol start="10" style="list-style-type: decimal">
<li><p>Vi har følgende informasjon fra to tilfeldige utvalg fra to ulike normalfordelte populasjoner: <span class="math inline">\(s_{1}^2 = 1400\)</span>, <span class="math inline">\(n_1 = 60\)</span>, <span class="math inline">\(s_{2}^2 = 700\)</span>, <span class="math inline">\(n_2 = 60\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Kan vi hevde at de to utvalgene har ulik varians? Bruk 5 % signifikansnivå.</p></li>
<li><p>Gjenta a., denne gangen med <span class="math inline">\(n_1 = 30\)</span> og <span class="math inline">\(n_2 = 30\)</span>.</p></li>
<li><p>Fastslå hva som er effekten på verdi av testobservator og konklusjon av testen når vi reduserer utvalgsstørrelse.</p></li>
</ol></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Her ønsker vi å test <span class="math inline">\(H_0: \sigma_{1}^2/\sigma_{2}^2 = 1\)</span> mot <span class="math inline">\(H_1: \sigma_{1}^2/\sigma_{2}^2 \neq 1\)</span>. Husk at for en tosidig test er det smart å formulere null- og alternativ hypotesen slik at den største utvalgsvariansen kommer i telleren til testobservatoren:</li>
</ol>
<p><span class="math display">\[F = s_{1}^2/s_{2}^2 = 1400/700 = 2\]</span></p>
<p>Da trenger vi nemlig kun å sammenligne testobservatoren med den øvre kvantilen i F-fordelingen. Forkastningsområdet blir i dette tilfellet <span class="math inline">\(F &gt; F_{0.025, 59, 59} = 1.67\)</span>. Siden <span class="math inline">\(F = 2\)</span> er større enn <span class="math inline">\(1.67\)</span> kan vi altså forkaste <span class="math inline">\(H_0\)</span> til fordel for <span class="math inline">\(H_1\)</span> på et 5 % signifikansnivå.</p>
</blockquote>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Forkastningsområdet er da <span class="math inline">\(F &gt; F_{0.025, 29, 29} = 2.1\)</span> og siden <span class="math inline">\(F &lt; 2.1\)</span> kan vi ikke forkaste <span class="math inline">\(H_0\)</span> på et 5 % signifikansnivå.</li>
</ol>
</blockquote>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Testobservatoren forblir uendret, men vi ser at den kritiske verdien som må overstiges for å få forkastning øker når antall observasjoner avtar. Konklusjonen blir derfor motsatt i oppgave b. Skulle vi fått forkastning også i b. måtte det reduserte utvalget blitt kompensert av et større avvik mellom <span class="math inline">\(s_1\)</span> og <span class="math inline">\(s_2\)</span>.</li>
</ol>
</blockquote>
<!-- qf(0.975, 59, 59) -->
<!-- qf(0.975, 29, 29) -->
</details>
<ol start="11" style="list-style-type: decimal">
<li>En bedrift som har en dyr leieavtale av en parkeringsplass vurderer innkjøp av elektroniske sparkesykler. Tanken er at de som bor nær bedriften da kan benytte seg av disse istedenfor å kjøre bil. I et prøveprosjekt får bedriften leid en rekke sparkesykler i 20 arbeidsdager og antall biler på parkeringsplassen blir registrert daglig. Den samme registreringen blir gjort de 20 påfølgende arbeidsdagene når sparkesyklene ikke er tilgjengelig. En ansatt som er ansvarlig for prøveprosjektet bruker R til å utføre to tester basert på data fra disse to registreringene.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Formuler null- og alternativhypotesen til den første testen. Hvorfor utfører den ansatte denne testen?</p></li>
<li><p>Formuler null- og alternativhypotesen samt testobservatoren til den andre testen. Trekk en praktisk konklusjon om innføringen av sparkesykler ut fra utskriften.</p></li>
</ol>
<pre><code>## 
##  F test to compare two variances
## 
## data:  uten_sparkesykkel and med_sparkesykkel
## F = 1.5385, num df = 19, denom df = 19, p-value = 0.3559
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.6089665 3.8870052
## sample estimates:
## ratio of variances 
##           1.538524</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  uten_sparkesykkel and med_sparkesykkel
## t = 2.4621, df = 38, p-value = 0.009232
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  2.525173      Inf
## sample estimates:
## mean of x mean of y 
##  39.91587  31.90524</code></pre>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>La <span class="math inline">\(\sigma^2_{1}\)</span> og <span class="math inline">\(\sigma^2_{2}\)</span> være populasjonsvariansene til antall biler som kommer for å parkere på henholdsvis dager der sparkesykler <em>ikke</em> er tilgjengelig og dager der sparkesykler er tilgjengelig. Utskriften viser da en test av <span class="math inline">\(H_0: \sigma^2_{1}/\sigma^2_{2} = 1\)</span> mot <span class="math inline">\(H_1: \sigma^2_{1}/\sigma^2_{2} \neq 1\)</span>.</li>
</ol>
<p>Den ansatte utfører denne testen for å se om han kan bruke varianten av to-utvalgs t-test som antar lik varians når vedkommende tester om innføringen av sparkesykler har noen effekt (se b.). Ut fra p-verdien på 0.3559 (altså ingen forkastning av <span class="math inline">\(H_0\)</span>) vil det være greit å bruke en slik test i dette tilfellet.</p>
<p>Tips: variabel navnet som står først i testen (“uten_sparkesykkel”) indikerer hvilke av de to variansen som står i telleren av <span class="math inline">\(\sigma^2_{1}/\sigma^2_{2}\)</span> (i <span class="math inline">\(H_0\)</span>) og <span class="math inline">\(s^2_{1}/s^2_{2}\)</span> (i testobservatoren) i testen R utfører.</p>
</blockquote>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>La <span class="math inline">\(\mu_1\)</span> og <span class="math inline">\(\mu_2\)</span> være forventet antall biler på henholdsvis dager der sparkesykler <em>ikke</em> er tilgjengelig og dager der sparkesykler er tilgjengelig. Utskriften viser en en-sidig, to-utvalgs t-test av hypotesen <span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span> mot <span class="math inline">\(H_1: \mu_1 - \mu_2 &gt; 0\)</span>. <span class="math inline">\(H_1\)</span> er altså om det forventes ferre biler på dager med sparkesykler enn på dager uten sparkesykler.</li>
</ol>
<p>“Two sample t-test” betyr at vi har antatt lik varians (ellers ville det stått “Welch two sample t-test”), og testobservatoren er derfor gitt ved:</p>
<p><span class="math display">\[T = \frac{\overline{x}_1 - \overline{x}_2 - 0}{\sqrt{s^2_{P}(1/n_1 + 1/n_2)}}\]</span></p>
<p>der <span class="math display">\[s^2_{P} = \frac{(n_1 - 1)s^2_{1} + (n_2 - 1)s^2_{2}}{n_1 + n_2 -2}\]</span></p>
<p>Ut fra p-verdien på 0.009232 forkaster vi <span class="math inline">\(H_0\)</span> på 1 % (!) signifikansnivå. Vi har med andre ord god grunn til å tro at en innføring av sparkesykler vil redusere antall biler på parkeringsplassen.</p>
<p>Tips: Variabelnavnet som står først (“uten_sparkesykkel”) indikerer hva som er første verdi i differansene <span class="math inline">\(\mu_1 - \mu_2\)</span> (i hypotesene) og <span class="math inline">\(\overline{x}_1 - \overline{x}_2\)</span> (i testobservatoren) i testen R utfører.</p>
</blockquote>
</details>
<ol start="12" style="list-style-type: decimal">
<li>Vi har følgende informasjon om fra to tilfeldige utvalg fra to populasjoner: I utvalg 1 har <span class="math inline">\(x_1 = 100\)</span> av <span class="math inline">\(n_1 = 200\)</span> individer et spesielt kjennetegn, mens i utvalg 2 er det det tilsvarende tallet <span class="math inline">\(x_2 = 90\)</span> av <span class="math inline">\(n_2 = 200\)</span>.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Utfør en test for å undersøke om de to populasjonene har ulik andel av kjennetegnet. Bruk 5 % signifikansnivå.</p></li>
<li><p>Regn ut p-verdien for testen over.</p></li>
<li><p>Gjenta a., denne gangen med <span class="math inline">\(x_1 = 190\)</span> og <span class="math inline">\(x_2 = 180\)</span>. Fastslå effekten på p-verdien av å øke andelene (dersom differansen er uendret).</p></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Vi skal her teste hypotsen <span class="math inline">\(H_0: p_1 - p_2 = 0\)</span> mot <span class="math inline">\(H_1: p_1 - p_2 \neq 0\)</span>. Med <span class="math inline">\(\hat{p_1} = 100/200 = 0.5\)</span>, <span class="math inline">\(\hat{p}_2 = 90/200 = 0.45\)</span> og <span class="math inline">\(\hat{p} = (100 + 90)/(200 + 200) = 0.475\)</span> er testobservatoren er gitt ved</li>
</ol>
</blockquote>
<blockquote>
<p><span class="math display">\[Z = \frac{\hat{p}_1 - \hat{p}_2}{\sqrt{\hat{p}(1-\hat{p})(1/n_1 + 1/n_2)}} = \frac{0.5 - 0.45}{\sqrt{0.475(1-0.475)(1/200 + 1/200)}}=1.00\]</span></p>
<p>Siden dette er en tosidig test er forkastningsområdet til testen <span class="math inline">\(|Z| &gt; z_{\alpha/2} = z_{0.025}=1.96\)</span>. Siden 1 &lt; 1.96 kan vi altså <em>ikke</em> forkaste <span class="math inline">\(H_0\)</span> ved 5 % signifikansnivå.</p>
</blockquote>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>P-verdier for tosidige tester kan være litt tricky å forstå. Vi er altså ute etter sannsynligheten for at noe “minst like ekstremt og til fordel for <span class="math inline">\(H_1\)</span> intreffer”. For en tosidig test ville vi også reagert på store negative verdier av <span class="math inline">\(Z\)</span>, og “minst like ekstremt” i negativ retning ville vært <span class="math inline">\(Z &lt; - 1.00\)</span>. Altså blir p-verdien</li>
</ol>
<p><span class="math display">\[p-verdi = P(Z &lt; -1.00\quad \text{og/eller}\quad Z &gt; 1.00)\\ = P(Z &lt; -1.00) + P(Z &gt; 1.00) = 2P(Z &gt; 1.00) = 2*(1 - 0.841) = 0.317\]</span></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Testobservatoren er da gitt ved</li>
</ol>
<p><span class="math display">\[Z = \frac{\hat{p}_1 - \hat{p}_2}{\sqrt{\hat{p}(1-\hat{p})(1/n_1 + 1/n_2)}} = \frac{0.95 - 0.90}{\sqrt{0.475(1-0.475)(1/200 + 1/200)}}=1.89\]</span></p>
<p>P-verdien er som før gitt ved</p>
<p><span class="math display">\[ P-value = 2P(Z &gt; 1.89) = 2*(1 - 0.97) = 0.06 \]</span></p>
<p>Vi ser at p-verdien avtar når andelene blir større. Vi er her ganske nære på å forkaste <span class="math inline">\(H_0\)</span> selv om differansen mellom <span class="math inline">\(\hat{p}_1\)</span> og <span class="math inline">\(\hat{p}_2\)</span> er den samme som i oppgave a. I nevneren til testobservatoren ser vi at variansen til differansen <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> er proposjonal med <span class="math inline">\(\hat{p}(1-\hat{p})\)</span>. Denne vil bli mindre når <span class="math inline">\(\hat{p}\)</span> nærmer seg 1 (eller 0), og er størst når <span class="math inline">\(\hat{p} = 0.5\)</span>. Vi er derfor sikrere på at differansen <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> i oppgave b. ligger nær den sanne differansen i populasjon sammenlignet med oppgave a. Bevismateriale mot <span class="math inline">\(H_1\)</span> øker (p-verdien går ned), men i dette tilfellet holder det ikke til å forkaste <span class="math inline">\(H_0\)</span>.</p>
</blockquote>
<!-- z = (0.5 - 0.45)/sqrt(0.475*(1 - 0.475)*(1/200 + 1/200)) -->
<!-- pval = 2*(1 - pnorm(z)) -->
<!-- z = (0.95 - 0.90)/sqrt(0.925*(1 - 0.925)*(1/200 + 1/200)) -->
<!-- pval = 2*(1 - pnorm(z)) -->
</details>
<ol start="13" style="list-style-type: decimal">
<li>En kredittutsteder gir kundene en rating basert på blant annet gjeld, formue og tidligere betalingsanmerkninger. Tanken er at en lav rating medfører høyere sannsynlighet mislighold av lånet sitt. For å sjekke om ratingen gir en reell indikasjon på mislighold, blir det registrert antall mislighold i et utvalg med rating under 800, og i et utvalg med rating 800 eller høyere.</li>
</ol>
<table>
<thead>
<tr class="header">
<th></th>
<th align="center">Rating &lt; 800</th>
<th align="center">Rating &gt; 800</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Utvalgsstørrelse</td>
<td align="center">612</td>
<td align="center">854</td>
</tr>
<tr class="even">
<td>Mislighold</td>
<td align="center">14</td>
<td align="center">9</td>
</tr>
</tbody>
</table>
<p>Kan vi konkludere med at personer med rating lavere enn 800 har høyere sannsynlighet for mislighold av lånet sitt sammenlignet med de med rating over 800? Bruk 5 % signifikansnivå.</p>
<details>
<summary>
Løsning
</summary>
<blockquote>
<p>La <span class="math inline">\(p_1\)</span> være sannsynlighet for mislighold for de med rating under 800 og la <span class="math inline">\(p_2\)</span> være den samme sannsynligheten for de med rating over 800. Vi skal da teste <span class="math inline">\(H_0: p_1 - p_2 = 0\)</span> mot det ensidige alternativet <span class="math inline">\(H_1: p_1 - p_2 &gt; 0\)</span>. Med <span class="math inline">\(\hat{p_1} = 14/612 = 0.0229\)</span>, <span class="math inline">\(\hat{p}_2 = 0.0105\)</span>, og <span class="math inline">\(\hat{p}=(14 + 9)/(612 + 854)=0.0157\)</span> er testobservatoren gitt ved</p>
<p><span class="math display">\[Z =  \frac{\hat{p}_1 - \hat{p}_2}{\sqrt{\hat{p}(1-\hat{p})(1/n_1 + 1/n_2)}} = \frac{0.0229 - 0.0105}{\sqrt{0.0157(1-0.0157)(1/612 + 1/854)}}=1.874\]</span></p>
<p>Forkastningsområdet er gitt ved <span class="math inline">\(Z &gt; z_\alpha = 1.645\)</span>, og siden 1.874 &gt; 1.645 forkaster vi <span class="math inline">\(H_0\)</span>. Det er grunn til å tro at personer med rating lavere enn 800 har større sannsynlighet for mislighold.</p>
</blockquote>
<!-- x1 = 14 -->
<!-- x2 = 9 -->
<!-- n1 = 612 -->
<!-- n2 = 854 -->
<!-- p1 = x1/n1 -->
<!-- p2 = x2/n2 -->
<!-- p = (x1 + x2)/(n1 + n2) -->
<!-- z = (p1 - p2)/sqrt(p*(1-p)*(1/n1 + 1/n2)) -->
</details>
<ol start="14" style="list-style-type: decimal">
<li>To konkurrerende selskaper, A og B, dominerer et marked for et bestemt produkt og har historisk sett hatt markedsandeler på hhv. 40 % og 50 % (altså 10 % til andre markeder). Selskap A gjennomfører så en markedsføringskampanje. For å avgjøre kampanjens effekt trekker et markedsanalyseselskap et tilfeldig utvalg av 300 kunder som spørres om deres produkt preferanse:</li>
</ol>
<table>
<thead>
<tr class="header">
<th align="center">Foretrukket selskap</th>
<th align="center">A</th>
<th align="center">B</th>
<th align="center">andre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Frekvens</td>
<td align="center">140</td>
<td align="center">142</td>
<td align="center">18</td>
</tr>
</tbody>
</table>
<p>Har markedsandelene endret seg?</p>
<details>
<summary>
Løsning
</summary>
<blockquote>
<p>Vi skal her test <span class="math inline">\(H_0: p_1 = 0.4, p_2 = 0.5, p_3 = 0.1\)</span> mot <span class="math inline">\(H_1:\)</span> minst to sannsynligheter er forskjellige. Utregning av testobservator blir da som følger:</p>
</blockquote>
<table>
<thead>
<tr class="header">
<th align="center">Foretrukket selskap</th>
<th align="center"><span class="math inline">\(f_i\)</span></th>
<th align="center"><span class="math inline">\(e_i\)</span></th>
<th align="center"><span class="math inline">\((f_i - e_i)^2/e_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">A</td>
<td align="center">140</td>
<td align="center"><span class="math inline">\(300\times 0.4 = 120\)</span></td>
<td align="center">3.3333</td>
</tr>
<tr class="even">
<td align="center">B</td>
<td align="center">142</td>
<td align="center"><span class="math inline">\(300\times 0.5 = 150\)</span></td>
<td align="center">0.4266</td>
</tr>
<tr class="odd">
<td align="center">andre</td>
<td align="center">18</td>
<td align="center"><span class="math inline">\(300\times 0.1 = 30\)</span></td>
<td align="center">4.8000</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
</tbody>
</table>
<blockquote>
<p>Forkastelsesområdet er <span class="math inline">\(\chi^2 &gt; \chi^2_{\alpha, k - 1} = \chi^2_{0.05, 2} = 5.99\)</span>. Siden <span class="math inline">\(\chi^2 = 8.564 &gt; 5.99\)</span> forkaster vi <span class="math inline">\(H_0\)</span> på 5 % signifikansnivå.</p>
</blockquote>
<!-- n=300 -->
<!-- p1=0.4 -->
<!-- p2 = 0.5 -->
<!-- p3 = 0.1 -->
<!-- f1 = 140 -->
<!-- f2 = 142 -->
<!-- f3 = 18 -->
<!-- f = c(f1,f2,f3) -->
<!-- p = c(p1, p2, p3)     -->
<!-- e = n*p -->
<!-- s = (f - e)^2/e -->
<!-- chi = sum(s) -->
<!-- q = qchisq(0.95, 2) -->
</details>
<ol start="15" style="list-style-type: decimal">
<li>Et produksjonsselskap har mulighet til å bruke tre forskjellige kjemikalier for å fremstille det samme produktet. Lederen ved produksjonsselskapet ønsker å undersøke hvorvidt det er forskjell på hvor mange mangelfulle produkter som blir produsert når en varierer bruken av type kjemikalier. Hun gjør et tilfeldig utvalg på 700 produkter og klassifiserer dem som enten tilfredsstillende eller mangelfull. Funnene er oppsummert i tabellen nedenfor:</li>
</ol>
<table>
<colgroup>
<col width="20%" />
<col width="20%" />
<col width="20%" />
<col width="20%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Klassifisering/kjemikalie</th>
<th align="center">Kjemikalie 1</th>
<th align="center">Kjemikalie 2</th>
<th align="center">Kjemikalie 3</th>
<th align="center">sum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Tilfredstillende</td>
<td align="center">268</td>
<td align="center">216</td>
<td align="center">164</td>
<td align="center">648</td>
</tr>
<tr class="even">
<td align="center">Mangelfull</td>
<td align="center">15</td>
<td align="center">17</td>
<td align="center">20</td>
<td align="center">52</td>
</tr>
<tr class="odd">
<td align="center">sum</td>
<td align="center">283</td>
<td align="center">233</td>
<td align="center">184</td>
<td align="center">700</td>
</tr>
</tbody>
</table>
<p>Utfør en test for å avgjøre om det er en sammenheng mellom mangelfulle produkter og kjemikalie brukt under produksjon.</p>
<details>
<summary>
Løsning
</summary>
<blockquote>
<p>Vi skal altså teste <span class="math inline">\(H_0:\)</span> <em>De to variablene klassfisering og kjemikalie er uavhengige</em> mot <span class="math inline">\(H_1:\)</span> <em>Variablene klassifisering og kjemikalie er avhengige</em>. Vi begynner med å regne ut de forventede frekvensene ved bruk av formelen <span class="math inline">\(e_{ij} = f_{i.}f_{.j}/n\)</span>:</p>
</blockquote>
<table>
<colgroup>
<col width="20%" />
<col width="20%" />
<col width="20%" />
<col width="20%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">klas./kjem.</th>
<th align="center">Kjem 1</th>
<th align="center">Kjem 2</th>
<th align="center">Kjem 3</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Tilfreds.</td>
<td align="center"><span class="math inline">\(e_{11} = 648\times 283/700 = 262.0\)</span></td>
<td align="center"><span class="math inline">\(e_{12} = 648\times 233/700 = 215.7\)</span></td>
<td align="center"><span class="math inline">\(e_{13} = 648\times 184/700 = 170.3\)</span></td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">Mangel.</td>
<td align="center"><span class="math inline">\(e_{21} = 52\times 283/700 = 21.0\)</span></td>
<td align="center"><span class="math inline">\(e_{22} = 52\times 233/700 = 17.3\)</span></td>
<td align="center"><span class="math inline">\(e_{23} = 52\times 184/700 = 13.7\)</span></td>
<td align="center"></td>
</tr>
</tbody>
</table>
<blockquote>
<p>Så regner vi ut hvert element <span class="math inline">\((f_{ij} - e_{ij})^2/e_{ij}\)</span> som skal inn i summen til test observatoren:</p>
</blockquote>
<table>
<thead>
<tr class="header">
<th align="center">klas./kjem.</th>
<th align="center">Kjem 1</th>
<th align="center">Kjem 2</th>
<th align="center">Kjem 3</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Tilfreds.</td>
<td align="center"><span class="math inline">\((268 - 262.0)^2/262 = 0.1384\)</span></td>
<td align="center">0.0004</td>
<td align="center">0.2353</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">Mangel.</td>
<td align="center">1.7255</td>
<td align="center">0.0055</td>
<td align="center">2.9327</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<blockquote>
<p>Testobservatoren er da gitt ved</p>
</blockquote>
<p><span class="math display">\[\chi^2 = \sum_{i = 1}^2\sum_{j = 1}^3(f_{ij} - e_{ij})^2/e_{ij} = 0.1385 + 0.0004 + 0.2352 + 1.7255 + 0.0055 + 2.9327 = 5.0378\]</span></p>
<blockquote>
<p>Forkastelsesområdet er <span class="math inline">\(\chi^2 &gt; \chi^2_{\alpha, (r - 1)(s - 1)} = \chi^2_{0.05, 2} = 5.99\)</span>. Siden <span class="math inline">\(\chi^2 = 5.0378 &lt; 5.99\)</span> forkaster vi <em>ikke</em> <span class="math inline">\(H_0\)</span> på 5 % signifikansnivå.</p>
<p>I R ville vi gjort følgende:</p>
</blockquote>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="oppgaver.html#cb72-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">268</span>, <span class="dv">216</span>, <span class="dv">164</span>, <span class="dv">15</span>, <span class="dv">17</span>, <span class="dv">20</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> T)</span>
<span id="cb72-2"><a href="oppgaver.html#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(f)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  f
## X-squared = 5.038, df = 2, p-value = 0.08054</code></pre>
<!-- n = 700 -->
<!-- f = matrix(c(268, 216, 164, 15, 17, 20), nrow = 2, ncol = 3, byrow = T) -->
<!-- for(i in 1:2){ -->
<!-- for(j in 1:3){ -->
<!-- e[i,j] = rowSums(f)[i]*colSums(f)[j]/n -->
<!-- } -->
<!-- } -->
<!-- chi = matrix(NA, nrow = 2, ncol = 3) -->
<!-- for(i in 1:2){ -->
<!-- for(j in 1:3){ -->
<!-- chi[i,j] = (f[i,j] - e[i,j])^2/e[i,j] -->
<!-- sum(chi) -->
<!-- chisq.test(f) #OK -->
</details>
<ol start="16" style="list-style-type: decimal">
<li><a href="tidligere-eksamensoppgaver/skole-21-v.pdf">Individuell eksamen V21, oppgave 1 a - c:</a>
<details>
<summary>
Løsning
</summary>
<a href="tidligere-eksamensoppgaver/skole-21-v-fasit.pdf">Løsningsforslag</a>
</details></li>
</ol>
<!-- **På Canvas finner du en .zip-fil som inneholder alle datasettene, samt løsningsforslag til oppgavene i læreboken.** -->
<!-- ```{r, echo = FALSE, message = FALSE} -->
<!-- library(dplyr) -->
<!-- options(knitr.kable.NA = '') -->
<!-- "oppgaver/oppgaver-hypotesetesting.xlsx" %>%  -->
<!--     readxl::read_excel() %>%  -->
<!--     kableExtra::kbl() %>%  -->
<!--     kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed")) -->
<!-- ``` -->
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="kjikvadrattester.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="relevante-r-testing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"toc_depth": 4
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
