<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.9 Oppgaver | MET4 - Empiriske Metoder - Vår 2023</title>
  <meta name="description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="5.9 Oppgaver | MET4 - Empiriske Metoder - Vår 2023" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.9 Oppgaver | MET4 - Empiriske Metoder - Vår 2023" />
  
  <meta name="twitter:description" content="Dette er hjemmesiden til kurset MET4 - Empiriske Metoder, som gis på bachelorstudiet ved Norges Handelshøyskole." />
  

<meta name="author" content="Håkon Otneim og Geir Drage Berentsen" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modellbygging-1.html"/>
<link rel="next" href="relevante-r-tidsrekker.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link rel="apple-touch-icon" sizes="180x180" href="/met4/icon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/met4/icon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/met4/icon/favicon-16x16.png">
<link rel="manifest" href="/met4/icon/site.webmanifest">
<link rel="mask-icon" href="/met4/icon/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/met4/icon/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/met4/icon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<a href="https://www.nhh.no/"><img src="bilder/nhh.png" width="240"></a>
<li><a href="./index.html">MET4 - EMPIRISKE METODER</a></li>

<li class="divider"></li>
<li><a href="index.html#innledning" id="toc-innledning">Innledning</a></li>
<li><a href="introduksjon-til-r.html#introduksjon-til-r" id="toc-introduksjon-til-r"><span class="toc-section-number">1</span> Introduksjon til R</a>
<ul>
<li><a href="en-gjennomgang-av-rstudio.html#en-gjennomgang-av-rstudio" id="toc-en-gjennomgang-av-rstudio"><span class="toc-section-number">1.1</span> En gjennomgang av RStudio</a></li>
<li><a href="enkle-beregninger-og-variabler.html#enkle-beregninger-og-variabler" id="toc-enkle-beregninger-og-variabler"><span class="toc-section-number">1.2</span> Enkle beregninger og variabler</a></li>
<li><a href="vektorer.html#vektorer" id="toc-vektorer"><span class="toc-section-number">1.3</span> Vektorer</a></li>
<li><a href="pakker.html#pakker" id="toc-pakker"><span class="toc-section-number">1.4</span> Pakker</a></li>
<li><a href="mappesti.html#mappesti" id="toc-mappesti"><span class="toc-section-number">1.5</span> Mappesti</a></li>
<li><a href="innlesing-av-data.html#innlesing-av-data" id="toc-innlesing-av-data"><span class="toc-section-number">1.6</span> Innlesing av data</a></li>
<li><a href="statistiske-analyser.html#statistiske-analyser" id="toc-statistiske-analyser"><span class="toc-section-number">1.7</span> Statistiske analyser</a></li>
<li><a href="r-plotting.html#r-plotting" id="toc-r-plotting"><span class="toc-section-number">1.8</span> Plotting</a></li>
<li><a href="script.html#script" id="toc-script"><span class="toc-section-number">1.9</span> Script</a></li>
<li><a href="pipe.html#pipe" id="toc-pipe"><span class="toc-section-number">1.10</span> Pipe-operatoren <code>%&gt;%</code> og enkel datavask</a></li>
<li><a href="r-ekstra.html#r-ekstra" id="toc-r-ekstra"><span class="toc-section-number">1.11</span> Oppsummering og ekstra oppgaver</a></li>
</ul></li>
<li><a href="grunnleggende-statistikk.html#grunnleggende-statistikk" id="toc-grunnleggende-statistikk"><span class="toc-section-number">2</span> Grunnleggende statistikk</a>
<ul>
<li><a href="deskriptiv-statistikk.html#deskriptiv-statistikk" id="toc-deskriptiv-statistikk"><span class="toc-section-number">2.1</span> Deskriptiv statistikk</a></li>
<li><a href="utvalg-og-estimering.html#utvalg-og-estimering" id="toc-utvalg-og-estimering"><span class="toc-section-number">2.2</span> Utvalg og estimering</a></li>
<li><a href="oppgaverdeskriptiv.html#oppgaverdeskriptiv" id="toc-oppgaverdeskriptiv"><span class="toc-section-number">2.3</span> Oppgaver</a></li>
<li><a href="relevant-r-grunnleggende.html#relevant-r-grunnleggende" id="toc-relevant-r-grunnleggende"><span class="toc-section-number">2.4</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="hypotesetesting.html#hypotesetesting" id="toc-hypotesetesting"><span class="toc-section-number">3</span> Hypotesetesting</a>
<ul>
<li><a href="generelt-om-hypotesetesting.html#generelt-om-hypotesetesting" id="toc-generelt-om-hypotesetesting"><span class="toc-section-number">3.1</span> Generelt om hypotesetesting</a></li>
<li><a href="enpop.html#enpop" id="toc-enpop"><span class="toc-section-number">3.2</span> Inferens om en populasjon</a></li>
<li><a href="inferens-om-to-populasjoner.html#inferens-om-to-populasjoner" id="toc-inferens-om-to-populasjoner"><span class="toc-section-number">3.3</span> Inferens om to populasjoner</a></li>
<li><a href="kjikvadrattester.html#kjikvadrattester" id="toc-kjikvadrattester"><span class="toc-section-number">3.4</span> Kjikvadrattester</a></li>
<li><a href="oppgaver.html#oppgaver" id="toc-oppgaver"><span class="toc-section-number">3.5</span> Oppgaver</a></li>
<li><a href="relevante-r-testing.html#relevante-r-testing" id="toc-relevante-r-testing"><span class="toc-section-number">3.6</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="regresjon.html#regresjon" id="toc-regresjon"><span class="toc-section-number">4</span> Regresjon</a>
<ul>
<li><a href="enkel-regresjon.html#enkel-regresjon" id="toc-enkel-regresjon"><span class="toc-section-number">4.1</span> Enkel regresjon</a></li>
<li><a href="multippel-regresjon.html#multippel-regresjon" id="toc-multippel-regresjon"><span class="toc-section-number">4.2</span> Multippel regresjon</a></li>
<li><a href="modellbygging.html#modellbygging" id="toc-modellbygging"><span class="toc-section-number">4.3</span> Modellbygging</a></li>
<li><a href="oppgaver-1.html#oppgaver-1" id="toc-oppgaver-1"><span class="toc-section-number">4.4</span> Oppgaver</a></li>
<li><a href="relevante-r-regresjon.html#relevante-r-regresjon" id="toc-relevante-r-regresjon"><span class="toc-section-number">4.5</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="tidsrekker.html#tidsrekker" id="toc-tidsrekker"><span class="toc-section-number">5</span> Tidsrekker</a>
<ul>
<li><a href="intro.html#intro" id="toc-intro"><span class="toc-section-number">5.1</span> Introduksjon til tidsrekker</a></li>
<li><a href="trend-og-sesong.html#trend-og-sesong" id="toc-trend-og-sesong"><span class="toc-section-number">5.2</span> Trend og sesong</a></li>
<li><a href="ar.html#ar" id="toc-ar"><span class="toc-section-number">5.3</span> AR(p)</a></li>
<li><a href="stasjonaritet.html#stasjonaritet" id="toc-stasjonaritet"><span class="toc-section-number">5.4</span> Stasjonaritet</a></li>
<li><a href="autokorrelasjon.html#autokorrelasjon" id="toc-autokorrelasjon"><span class="toc-section-number">5.5</span> Autokorrelasjon</a></li>
<li><a href="ma.html#ma" id="toc-ma"><span class="toc-section-number">5.6</span> MA(q)</a></li>
<li><a href="arma-arima.html#arma-arima" id="toc-arma-arima"><span class="toc-section-number">5.7</span> ARMA og ARIMA</a></li>
<li><a href="modellbygging-1.html#modellbygging-1" id="toc-modellbygging-1"><span class="toc-section-number">5.8</span> Modellbygging</a></li>
<li><a href="oppgaver-2.html#oppgaver-2" id="toc-oppgaver-2"><span class="toc-section-number">5.9</span> Oppgaver</a></li>
<li><a href="relevante-r-tidsrekker.html#relevante-r-tidsrekker" id="toc-relevante-r-tidsrekker"><span class="toc-section-number">5.10</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="avansert-regresjon-og-maskinlæring.html#avansert-regresjon-og-maskinlæring" id="toc-avansert-regresjon-og-maskinlæring"><span class="toc-section-number">6</span> Avansert regresjon og maskinlæring</a>
<ul>
<li><a href="logistisk-regresjon.html#logistisk-regresjon" id="toc-logistisk-regresjon"><span class="toc-section-number">6.1</span> Logistisk regresjon</a></li>
<li><a href="introduksjon-til-maskinlæring-med-knn.html#introduksjon-til-maskinlæring-med-knn" id="toc-introduksjon-til-maskinlæring-med-knn"><span class="toc-section-number">6.2</span> Introduksjon til maskinlæring med kNN</a></li>
<li><a href="paneldata.html#paneldata" id="toc-paneldata"><span class="toc-section-number">6.3</span> Paneldata</a></li>
<li><a href="oppgaver-3.html#oppgaver-3" id="toc-oppgaver-3"><span class="toc-section-number">6.4</span> Oppgaver</a></li>
<li><a href="relevante-r-avansert-regresjon.html#relevante-r-avansert-regresjon" id="toc-relevante-r-avansert-regresjon"><span class="toc-section-number">6.5</span> Relevante R-kommandoer</a></li>
</ul></li>
<li><a href="dataøvinger.html#dataøvinger" id="toc-dataøvinger"><span class="toc-section-number">7</span> Dataøvinger</a>
<ul>
<li><a href="dataøving-1.html#dataøving-1" id="toc-dataøving-1"><span class="toc-section-number">7.1</span> Dataøving 1</a></li>
<li><a href="dataøving-2.html#dataøving-2" id="toc-dataøving-2"><span class="toc-section-number">7.2</span> Dataøving 2</a></li>
<li><a href="dataøving-3.html#dataøving-3" id="toc-dataøving-3"><span class="toc-section-number">7.3</span> Dataøving 3</a></li>
<li><a href="dataøving-4.html#dataøving-4" id="toc-dataøving-4"><span class="toc-section-number">7.4</span> Dataøving 4</a></li>
<li><a href="dataøving-5.html#dataøving-5" id="toc-dataøving-5"><span class="toc-section-number">7.5</span> Dataøving 5</a></li>
</ul></li>
<li><a href="seminar.html#seminar" id="toc-seminar"><span class="toc-section-number">8</span> Seminaroppgaver</a>
<ul>
<li><a href="seminar-1-grunnleggende-statistikk.html#seminar-1---grunnleggende-statistikk" id="toc-seminar-1---grunnleggende-statistikk"><span class="toc-section-number">8.1</span> Seminar 1 - Grunnleggende statistikk</a></li>
<li><a href="seminar-2-hypotesetesting.html#seminar-2---hypotesetesting" id="toc-seminar-2---hypotesetesting"><span class="toc-section-number">8.2</span> Seminar 2 - Hypotesetesting</a></li>
<li><a href="seminar-3-regresjon-i.html#seminar-3---regresjon-i" id="toc-seminar-3---regresjon-i"><span class="toc-section-number">8.3</span> Seminar 3 - Regresjon I</a></li>
<li><a href="seminar-4-regresjon-ii.html#seminar-4---regresjon-ii" id="toc-seminar-4---regresjon-ii"><span class="toc-section-number">8.4</span> Seminar 4 - Regresjon II</a></li>
<li><a href="seminar-5-tidsrekker.html#seminar-5---tidsrekker" id="toc-seminar-5---tidsrekker"><span class="toc-section-number">8.5</span> Seminar 5 - Tidsrekker</a></li>
<li><a href="seminar-6-avansert-regresjon-og-maskinlæring.html#seminar-6---avansert-regresjon-og-maskinlæring" id="toc-seminar-6---avansert-regresjon-og-maskinlæring"><span class="toc-section-number">8.6</span> Seminar 6 - Avansert regresjon og maskinlæring</a></li>
</ul></li>
<li><a href="eksamensoppgaver.html#eksamensoppgaver" id="toc-eksamensoppgaver"><span class="toc-section-number">9</span> Eksamensoppgaver</a>
<ul>
<li><a href="skoleeksamen.html#skoleeksamen" id="toc-skoleeksamen"><span class="toc-section-number">9.1</span> Tidligere eksamensoppgaver (skoleeksamen)</a></li>
<li><a href="tidligere-eksamensoppgaver-hjemmeeksamen.html#tidligere-eksamensoppgaver-hjemmeeksamen" id="toc-tidligere-eksamensoppgaver-hjemmeeksamen"><span class="toc-section-number">9.2</span> Tidligere eksamensoppgaver (hjemmeeksamen)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.nhh.no/en/employees/faculty/hakon-otneim/">Håkon Otneim</a></li>
<li><a href="https://www.nhh.no/en/employees/faculty/geir-drage-berentsen/">Geir Drage Berentsen</a></li>
<li><a href="https://github.com/rstudio/bookdown">
Publisert ved hjelp av bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MET4 - Empiriske Metoder - Vår 2023</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="oppgaver-2" class="section level2" number="5.9">
<h2><span class="header-section-number">5.9</span> Oppgaver</h2>
<ol style="list-style-type: decimal">
<li>Første ordens autokorrelasjon til en tidsrekke <span class="math inline">\(Y_t\)</span> er lik <span class="math inline">\(-0.5\)</span>. Andre ordens autokorrelasjon er lik <span class="math inline">\(0.3\)</span>.
<ol style="list-style-type: lower-alpha">
<li>Tegn opp grafen til autokorrelasjonsfunksjonen til <span class="math inline">\(Y_t\)</span>.</li>
<li>Forklar med ord hva det vil si at autokorrelasjonsfunksjonen til <span class="math inline">\(Y_t\)</span> ser slik ut for <em>observerte</em> verdier av <span class="math inline">\(Y_t\)</span>.</li>
<li>Forklar hva som er forskjellen på autokorrelasjonsfunksjonen til <span class="math inline">\(Y_t\)</span> og den <em>empiriske</em> autokorrelasjonen til <span class="math inline">\(Y_t\)</span> som vi har regnet ut for eksempel ved hjelp av 100 observerte realiseringer av tidsrekken.</li>
<li>Tegn opp en graf som kunne vært den empiriske autokorrelasjonsfunksjonen til <span class="math inline">\(Y_t\)</span> regnet ut for eksempel ved hjelp av 100 observerte realiseringer av tidsrekken.</li>
</ol></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Graf av autokorrelasjonen:</li>
</ol>
</blockquote>
<p><img src="bilder/tidsrekkeoppgaver1.png" width="500" /></p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>Første ordens autokorrelasjon er lik <span class="math inline">\(-0.5\)</span>, noe som betyr at korrelasjonen mellom påfølgende observerte verdier av <span class="math inline">\(Y_t\)</span> er lik <span class="math inline">\(-0.5\)</span>. I praksis betyr det at to påfølgende observasjoner vil ha en tendens til å være ganske forskjellige fra hverandre. Hvis <span class="math inline">\(Y_t\)</span> er “liten” (på en eller annen relevant skala), så vil <span class="math inline">\(Y_{t+1}\)</span> ha en tendens til å være “stor”. Og hvis <span class="math inline">\(Y_{t+1}\)</span> er “stor”, ja da vil <span class="math inline">\(Y_{t+2}\)</span> igjen ha en tendens til å være “liten”.</p>
<p>Andre ordens autokorrelasjon er lik <span class="math inline">\(0.3\)</span>, noe som betyr at korrelasjonen mellom to observasjoner som er observert med ett tidssteg mellom seg er lik <span class="math inline">\(0.3\)</span>. I praksis betyr det at dersom <span class="math inline">\(Y_t\)</span> er “liten”, så vil <span class="math inline">\(Y_{t+2}\)</span> også ha en tendens til å være “liten”, men denne tendensen er noe svakere enn den som er mellom to påfølgende observasjoner, der absoluttverdien til autokorrelasjonen er <span class="math inline">\(0.5\)</span>.</p>
<p>For eksempel kan vi tenke oss at en realisering av <span class="math inline">\(Y_t\)</span> ser slik ut:</p></li>
</ol>
</blockquote>
<p><img src="bilder/tidsrekkeoppgaver2.png" width="500" /></p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li><p>Dette er samme type spørsmål som vi kjenner til med forventningsverdi/gjennomsnitt, samt teoretisk og empirisk varians. En stokastisk variabel <span class="math inline">\(X\)</span> har en forventningsverdi <span class="math inline">\(\mu\)</span> og en varians <span class="math inline">\(\sigma^2\)</span>, men disse er i praksis ukjente. Vi kan derimot <em>estimere</em> forventningsverdien ved å ta et gjennomsnitt <span class="math inline">\(\overline X\)</span>, og vi kan <em>estimere</em> den teoretiske variansen ved å regne ut den <em>empiriske</em> variansen <span class="math inline">\(s^2\)</span>. Store talls lov garanterer at dette er gode estimater, ved at <span class="math inline">\(\overline X \rightarrow \mu\)</span> og <span class="math inline">\(s^2 \rightarrow \sigma^2\)</span> når antall observasjoner går mot uendelig.</p>
<p>Vi har nøyaktig det samme forholdet mellom empiriske og teoretiske autokorrelasjoner. Autokorrelasjonsfunksjonen til <span class="math inline">\(Y_t\)</span> som vi beskrev over er den teoretiske, og den er ikke kjent i praksis med mindre vi simulerer fra en kjent tidsrekkemodell.</p>
<p>For et gitt datasett kan vi derimot regne ut den empiriske autokorrelasjonsfunksjonen, som er et <em>estimat</em> av det sanne, teoretiske autokorrelasjonsfunksjonen. Vi vet, fra store talls lov, at dette er et godt estimat som vil konvergere mot sannheten etter hvert som vi får flere og flere observasjoner.</p></li>
<li><p>Den empiriske autokorrelasjonsfunksjonen vil ligne på den sanne autokorrelasjonsfunksjonen som vi tegnet opp over, men det vil være noe estimeringsfeil i tillegg som kommer av at vi bare har et endelig antall observasjoner. Laggene med null korrelasjon vil ikke måles til å ha <em>eksakt</em> null autokorrelasjon, men bare om lag 5% av dem vil havne utenfor forkastningsgrensene på 5% signifikansnivå. Vi tegner også inn noen tenkte forkastningsgrenser i figuren.</p></li>
</ol>
</blockquote>
<img src="bilder/tidsrekkeoppgaver3.png" width="500" />
</details>
<ol start="2" style="list-style-type: decimal">
<li>Vurdere hvilke(n) tidsrekkemodell(er) som passer til de empiriske autokorrelasjonsplottene under, regnet ut ved hjelp av <span class="math inline">\(n=500\)</span> observasjoner.</li>
</ol>
<p><img src="met4_files/figure-html/unnamed-chunk-181-1.png" width="960" /></p>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li><p>Vi har et statistisk signifikant negativt utslag på første lag, og et statistisk signifikant positivt utslag på andre lag. Det er ingen flere lags der autokorrelasjonsfunksjonen er stiatistisk signifikant forskjellig fra null. Det kan tyde på en MA(2)-prosess, med <span class="math inline">\(\theta_1 &lt;0\)</span> og <span class="math inline">\(\theta_2&gt;0\)</span>.</p></li>
<li><p>Autokorrelasjonsfunksjonen går sakte mot null med økende lag. Det kan tyde på en autoregressiv prosess, muligens en AR(1)-prosess med <span class="math inline">\(\phi_1 &gt; 0\)</span>.</p></li>
<li><p>Autokorrelasjonsfunksjonen alternerer mellom positive og negative verdier, men i absoluttverdi ser de ut til å avta sakte mot null. Det kan tyde på en autoregressiv prosess, muligens en AR(1)-prosess med <span class="math inline">\(\phi_1 &lt; 0\)</span>.</p></li>
</ol>
<p>Det er ikke mulig å entydig fastslå hvilken modell som er “korrekt” ut fra et autokorrelasjonsplott. I alle tilfellene kan det være AR- eller MA-ledd som har for små koeffisienter, til at vi klarer å estimere dem til å være statistisk signifikant forskjellig fra null ved hjelp av datasettet som vi har. Det er også vanskelig å visuelt skille høyere ordens prosesser fra hverandre kun ved å se på autokorrelasjonsplottet. I det midterste plottet over for eksempel, kunne det like gjerne vært med andre- og tredjeordens AR-ledd, uten at vi ville klart å se så stor forskjell på plottet.</p>
<p>(I denne oppgaven er datasettene 500 observasjoner simulert fra henholdsvis en MA(2)-modell med <span class="math inline">\(\theta_1 = -0.2279\)</span> og <span class="math inline">\(\theta_2 = 0.2488\)</span>, en AR(1)-modell med <span class="math inline">\(\phi_1 = 0.588\)</span>, og en AR(1)-modell med <span class="math inline">\(\phi_1 = -0.5\)</span>.)</p>
</blockquote>
</details>
<ol start="3" style="list-style-type: decimal">
<li>Under har vi anvendt funksjonen <code>auto.arima</code> fra <code>forecast</code>-pakken for fire tidsrekker. Identifiser hvilken modell som er plukket ut i hvert tilfelle, og skriv den opp:</li>
</ol>
<pre><code>## Series: ts 
## ARIMA(1,0,1) with zero mean 
## 
## Coefficients:
##          ar1      ma1
##       0.4307  -0.6955
## s.e.  0.2427   0.1922
## 
## sigma^2 estimated as 0.8962:  log likelihood=-135.48
## AIC=276.97   AICc=277.22   BIC=284.78</code></pre>
<pre><code>## Series: ts 
## ARIMA(2,0,1) with zero mean 
## 
## Coefficients:
##          ar1     ar2      ma1
##       0.3037  0.4736  -0.5945
## s.e.  0.1447  0.0871   0.1489
## 
## sigma^2 estimated as 0.9683:  log likelihood=-139.01
## AIC=286.01   AICc=286.43   BIC=296.43</code></pre>
<pre><code>## Series: ts 
## ARIMA(1,1,0) 
## 
## Coefficients:
##          ar1
##       0.3568
## s.e.  0.0933
## 
## sigma^2 estimated as 1.01:  log likelihood=-141.96
## AIC=287.92   AICc=288.04   BIC=293.13</code></pre>
<pre><code>## Series: ts 
## ARIMA(2,1,2) with drift 
## 
## Coefficients:
##           ar1     ar2     ma1     ma2    drift
##       -0.0001  0.4345  0.2207  0.8386  -0.7286
## s.e.   0.0996  0.1023  0.0609  0.0730   0.3520
## 
## sigma^2 estimated as 1.027:  log likelihood=-142.71
## AIC=297.43   AICc=298.33   BIC=313.06</code></pre>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li><p>En ARMA(1,1)-modell:</p>
<p><span class="math display">\[Y_t = 0.4307Y_{t-1} - 0.6955u_{t-1} + u_t,\]</span></p></li>
<li><p>En ARMA(2,1)-modell:</p>
<p><span class="math display">\[Y_t = 0.3037Y_{t-1} + 0.4736Y_{t-2} - 0.5945u_{t-1} + u_t,\]</span></p></li>
<li><p>En ARIMA(1,1,0)-modell:</p>
<p><span class="math display">\[\Delta Y_t = 0.3568\Delta Y_{t-1} + u_t,\]</span></p>
<p>der <span class="math inline">\(\Delta Y_t\)</span> er tidsrekken <span class="math inline">\(Y_t\)</span> differensiert en gang. Med andre ord er førstedifferansen til <span class="math inline">\(Y_t\)</span> en AR(1) prosess med <span class="math inline">\(\phi_1 = 0.3568\)</span>.</p></li>
<li><p>En ARIMA(2,1,2)-modell:</p>
<p><span class="math display">\[\Delta Y_t = -0.0001\Delta Y_{t-1} + 0.4345\Delta Y_{t-2} + 0.8386u_{t-1} - 0.7286u_{t-2},\]</span></p>
<p>Med andre ord er førstedifferansen til <span class="math inline">\(Y_t\)</span> en ARMA(2,2)-modell.</p></li>
</ol>
<p>I alle tilfellene er <span class="math inline">\(u_t\)</span> hvit støy.</p>
</blockquote>
</details>
<ol start="4" style="list-style-type: decimal">
<li>Regn ut forventning og varians til følgende tidsrekkemodeller og avgjør om de er stasjonære. I alle tilfeller er <span class="math inline">\(u_t\)</span> hvit støy der <span class="math inline">\(E(u_t)=0\)</span> og <span class="math inline">\(Var(u_t)=\sigma^2\)</span>.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(Y_t = t + u_t\)</span></li>
<li><span class="math inline">\(Y_t = 3 + u_t\)</span></li>
<li><span class="math inline">\(Y_t = t\cdot u_t\)</span></li>
<li><span class="math inline">\(Y_t = u_1 + u_2 + \dots + u_t\)</span></li>
</ol>
<details>
<summary>
Løsning
</summary>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li><span class="math display">\[E(Y_t) = E(t + u_t) = E(t) + E(u_t) = t + 0 = t.\]</span>
<span class="math display">\[Var(Y_t) = Var(t + u_t) = Var(t) + Var(u_t) = 0 + \sigma^2 = \sigma^2\]</span></li>
</ol>
<p>Siden forventningsverdien ikke er konstant kan ikke dette være en stasjonær tidsrekke.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li></li>
</ol>
<p><span class="math display">\[E(Y_t) = E(3 + u_t) = E(3) + E(u_t) = 3 + 0 = 3.\]</span>
<span class="math display">\[Var(Y_t) = Var(3 + u_t) = Var(3) + Var(u_t) = 0 + \sigma^2 = \sigma^2\]</span></p>
<p>Her er både forventning og varians konstant i tid så dette kan være en stasjonær tidsrekke (vi må formelt også sjekke at autokorrelasjonen er konstant)</p>
<ol start="3" style="list-style-type: lower-alpha">
<li></li>
</ol>
<p><span class="math display">\[E(Y_t) = E(t\cdot u_t) = t \cdot E(u_t) = t\cdot 0 = 0.\]</span>
<span class="math display">\[Var(Y_t) = Var(t\cdot u_t) = t^2\cdot Var(u_t) = t^2\sigma^2 \]</span></p>
<p>Siden varians ikke er konstant i tid kan ikke dette være en stasjonær tidsrekke.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li></li>
</ol>
<p><span class="math display">\[E(Y_t) = E(u_1 + u_2 + \dots + u_t) = E(u_1) + E(u_2) + \cdot + E(u_t) = 0 + 0 + \dots + 0 = 0.\]</span>
<span class="math display">\[\begin{align*}
Var(Y_t) &amp;= Var(u_1 + u_2 + \dots + u_t) \\
&amp; = Var(u_1) + Var(u_2) + \dots + Var(u_t) = \sigma^2 + \sigma^2 + \dots + \sigma^2 = t\sigma^2
\end{align*}\]</span>
Siden variansen ikke er konstant i tid kan ikke dette være en stasjonær tidsrekke.</p>
</blockquote>
</details>
<ol start="5" style="list-style-type: decimal">
<li><a href="tidligere-eksamensoppgaver/skole-21-v.pdf">Individuell eksamen V21, oppgave 3</a>
<details>
<summary>
Løsning
</summary>
<a href="tidligere-eksamensoppgaver/skole-21-v-fasit.pdf">Løsningsforslag</a>
</details></li>
<li><a href="tidligere-eksamensoppgaver/skole-20-v.pdf">Individuell eksamen V20, oppgave 3</a>
<details>
<summary>
Løsning
</summary>
<a href="tidligere-eksamensoppgaver/skole-20-v-fasit.pdf">Løsningsforslag</a>
</details></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modellbygging-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="relevante-r-tidsrekker.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"toc_depth": 4
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
